### ISSUE TITLE
Feature request: load last x messages

### ISSUE THREAD

**Issue by Aesculapius** [timotk/tweakstream#1]
Hoi,

het zou bij het in de gaten houden van wat tragere topics imho handig zijn als je kan aangeven hoeveel laatste posts hij moet laten zien, zodat je duidelijke context hebt van het topic waar je naar kijkt.

Ook bijv. bij 'tweakstream list', dan keuze topic, dan keuze hoeveel laatste berichten met bijv. default 5 ofzo.

Verder een top idee!

**Comment by timotk** [comment]
Bedankt voor de feedback! De commando structuur wil ik sowieso veranderen om het beter uitbreidbaar te maken.

**Comment by timotk** [comment]
@Aesculapius 
Ik heb je request toegevoegd aan de nieuwste versie. Je kan nu bij elk commando `--last [x]` toevoegen om de laatste x berichten te laten zien. Ik heb de default op 3 gezet.
